import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "ur";

const dict = {
  en: {
    nav_services: "Services",
    nav_portfolio: "Portfolio",
    nav_contact: "Contact",
    nav_signin: "Sign In",
    nav_dashboard: "Dashboard",
    hero_badge: "Professional Web Development",
    hero_title_1: "We Build Websites",
    hero_title_2: "That Convert",
    hero_sub: "From stunning single-page sites to full-scale e-commerce platforms, ReadzRaw delivers professional web solutions starting at just",
    hero_cta1: "View Packages",
    hero_cta2: "Contact Us",
    stat1: "Projects Delivered",
    stat2: "Client Satisfaction",
    stat3: "Fast Delivery",
    services_tag: "Our Packages",
    services_title_1: "Choose Your",
    services_title_2: "Perfect Plan",
    services_sub: "Transparent pricing with no hidden fees. Pay 50% upfront and the rest on delivery.",
    plan_starter: "Starter — 1 Page",
    plan_business: "Business — 4 Pages",
    plan_premium: "Premium — 10 Pages",
    plan_starter_desc: "A sleek single-page website perfect for personal portfolios, landing pages, or event pages. Fast delivery and mobile-responsive.",
    plan_business_desc: "A complete business website with multiple pages — Home, About, Services, and Contact. Ideal for small businesses and startups looking for a professional online presence.",
    plan_premium_desc: "A full-scale website with up to 10 pages, payment gateway integration (Stripe / JazzCash / EasyPaisa), product listings, and admin dashboard. Perfect for e-commerce and SaaS businesses.",
    feat_responsive: "Fully responsive design",
    feat_uiux: "Modern UI / UX",
    feat_contact: "Contact form integration",
    feat_seo: "SEO optimized",
    feat_rev1: "1 revision round",
    feat_rev3: "3 revision rounds",
    feat_rev5: "5 revision rounds",
    feat_delivery: "Delivered in 15 days",
    feat_4pages: "4 custom-designed pages",
    feat_devices: "Responsive on all devices",
    feat_blog: "Blog-ready layout",
    feat_social: "Social media integration",
    feat_maps: "Google Maps & analytics",
    feat_10pages: "Up to 10 custom pages",
    feat_gateway: "Payment gateway (Stripe/JazzCash/EasyPaisa)",
    feat_listings: "Product / service listings",
    feat_admin: "Admin dashboard",
    feat_auth: "User authentication",
    feat_email: "Email notifications",
    feat_support: "Priority support",
    order_title: "Order",
    order_confirmed: "Order Confirmed!",
    total: "Total",
    advance: "Advance (50%)",
    full_name: "Full Name",
    email: "Email",
    phone: "Phone",
    business_name: "Business Name",
    project_details: "Project Details",
    continue_payment: "Continue to Payment",
    submitting: "Submitting...",
    send_advance: "Send",
    via_easypaisa: "(50% advance) via EasyPaisa to:",
    account_label: "Account: EasyPaisa — ReadzRaw",
    after_payment: "After sending the payment, take a screenshot of the receipt and continue to upload it.",
    sent_payment: "I've Sent Payment — Upload Receipt",
    go_back: "Go Back",
    trx_label: "Transaction ID (TRX)",
    trx_help: "You'll find this in the confirmation SMS from EasyPaisa after sending payment.",
    upload_receipt: "Click to upload your payment receipt",
    submit_receipt: "Submit Receipt",
    uploading: "Uploading...",
    payment_submitted: "Payment Submitted!",
    verify_note: "We'll verify your receipt and start right away.",
    invoice: "READZRAW — INVOICE",
    billed_to: "Billed to",
    package: "Package",
    delivery_window: "Delivery window",
    days_15: "15 days",
    trx_id: "Transaction ID",
    advance_paid: "Advance paid (50%)",
    balance_delivery: "Balance on delivery",
    invoice_note: "Save this invoice — you'll need the invoice number for any support query.",
    questions: "Questions? Contact us at",
    done: "Done",
    tc_title: "Terms & Conditions",
    tc_updated: "Last updated: March 3, 2026",
    tc_s1_t: "1. Acceptance of Terms",
    tc_s1: "By accessing and using ReadzRaw's website and services at readzraw.lovable.app, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use our services.",
    tc_s2_t: "2. Services",
    tc_s2: "ReadzRaw provides professional web development services including but not limited to landing pages, business websites, e-commerce websites, and custom web applications. Service details, pricing, and deliverables are outlined in individual project agreements.",
    tc_s3_t: "3. Orders & Payments",
    tc_s3: "All orders require an advance payment as specified during checkout. The advance amount is non-refundable once work has commenced. Full payment is due upon project completion and before final delivery of source files and deployment.",
    tc_s4_t: "4. Client Responsibilities",
    tc_s4: "Clients must provide accurate project requirements, necessary content (text, images, branding assets), and timely feedback. Delays caused by late client input may extend delivery timelines.",
    tc_s5_t: "5. Intellectual Property",
    tc_s5: "Upon full payment, all custom-developed code, designs, and assets created specifically for the client's project are transferred to the client. ReadzRaw retains the right to showcase completed projects in its portfolio unless otherwise agreed in writing.",
    tc_s6_t: "6. Revisions",
    tc_s6: "Each service plan includes a specified number of revision rounds. Additional revisions beyond the included amount may incur extra charges as communicated in advance.",
    tc_s7_t: "7. Limitation of Liability",
    tc_s7: "ReadzRaw shall not be liable for any indirect, incidental, or consequential damages arising from the use of our services. Our total liability is limited to the amount paid by the client for the specific project in question.",
    tc_s8_t: "8. Termination",
    tc_s8: "Either party may terminate a project agreement with written notice. In case of termination, the client is responsible for payment of work completed up to the termination date. Advance payments are non-refundable.",
    tc_s9_t: "9. Governing Law",
    tc_s9: "These terms are governed by and construed in accordance with the laws of Pakistan. Any disputes shall be resolved through good-faith negotiation before pursuing formal legal action.",
    tc_s10_t: "10. Contact",
    tc_s10: "For questions about these Terms & Conditions, contact us at",
  },
  ur: {
    nav_services: "خدمات",
    nav_portfolio: "پورٹ فولیو",
    nav_contact: "رابطہ",
    nav_signin: "سائن اِن",
    nav_dashboard: "ڈیش بورڈ",
    hero_badge: "پروفیشنل ویب ڈیولپمنٹ",
    hero_title_1: "ہم بناتے ہیں ویب سائٹس",
    hero_title_2: "جو کاروبار بڑھائیں",
    hero_sub: "خوبصورت سنگل پیج سائٹس سے لے کر مکمل ای کامرس پلیٹ فارم تک — ReadzRaw پیش کرتا ہے پروفیشنل ویب سلوشنز، صرف",
    hero_cta1: "پیکجز دیکھیں",
    hero_cta2: "رابطہ کریں",
    stat1: "مکمل پروجیکٹس",
    stat2: "کلائنٹ اطمینان",
    stat3: "تیز ڈیلیوری",
    services_tag: "ہمارے پیکجز",
    services_title_1: "منتخب کریں",
    services_title_2: "بہترین پلان",
    services_sub: "شفاف قیمتیں، کوئی چھپی ہوئی فیس نہیں۔ 50% ایڈوانس اور باقی ڈیلیوری پر۔",
    plan_starter: "اسٹارٹر — 1 پیج",
    plan_business: "بزنس — 4 پیجز",
    plan_premium: "پریمیم — 10 پیجز",
    plan_starter_desc: "ایک خوبصورت سنگل پیج ویب سائٹ — ذاتی پورٹ فولیو، لینڈنگ پیج یا ایونٹ پیج کے لیے بہترین۔ تیز ڈیلیوری اور موبائل فرینڈلی۔",
    plan_business_desc: "مکمل بزنس ویب سائٹ — ہوم، اباؤٹ، سروسز اور رابطہ پیجز کے ساتھ۔ چھوٹے کاروبار اور اسٹارٹ اپس کے لیے مثالی۔",
    plan_premium_desc: "10 پیجز تک کی مکمل ویب سائٹ — پیمنٹ گیٹ وے (Stripe / JazzCash / EasyPaisa)، پروڈکٹ لسٹنگز اور ایڈمن ڈیش بورڈ کے ساتھ۔ ای کامرس اور SaaS کے لیے بہترین۔",
    feat_responsive: "مکمل ریسپانسیو ڈیزائن",
    feat_uiux: "جدید UI / UX",
    feat_contact: "رابطہ فارم انضمام",
    feat_seo: "SEO آپٹمائزڈ",
    feat_rev1: "1 ریویژن راؤنڈ",
    feat_rev3: "3 ریویژن راؤنڈز",
    feat_rev5: "5 ریویژن راؤنڈز",
    feat_delivery: "15 دن میں ڈیلیوری",
    feat_4pages: "4 کسٹم ڈیزائن پیجز",
    feat_devices: "ہر ڈیوائس پر ریسپانسیو",
    feat_blog: "بلاگ ریڈی لے آؤٹ",
    feat_social: "سوشل میڈیا انضمام",
    feat_maps: "گوگل میپس اور تجزیات",
    feat_10pages: "10 کسٹم پیجز تک",
    feat_gateway: "پیمنٹ گیٹ وے (Stripe/JazzCash/EasyPaisa)",
    feat_listings: "پروڈکٹ / سروس لسٹنگز",
    feat_admin: "ایڈمن ڈیش بورڈ",
    feat_auth: "یوزر آتھینٹیکیشن",
    feat_email: "ای میل نوٹیفیکیشنز",
    feat_support: "ترجیحی سپورٹ",
    order_title: "آرڈر",
    order_confirmed: "آرڈر کنفرم!",
    total: "کل رقم",
    advance: "ایڈوانس (50%)",
    full_name: "پورا نام",
    email: "ای میل",
    phone: "فون",
    business_name: "کاروبار کا نام",
    project_details: "پروجیکٹ کی تفصیل",
    continue_payment: "پیمنٹ کی طرف جائیں",
    submitting: "جمع ہو رہا ہے...",
    send_advance: "بھیجیں",
    via_easypaisa: "(50% ایڈوانس) EasyPaisa کے ذریعے:",
    account_label: "اکاؤنٹ: EasyPaisa — ReadzRaw",
    after_payment: "پیمنٹ بھیجنے کے بعد رسید کا اسکرین شاٹ لیں اور اپ لوڈ کریں۔",
    sent_payment: "پیمنٹ بھیج دی — رسید اپ لوڈ کریں",
    go_back: "واپس جائیں",
    trx_label: "ٹرانزیکشن آئی ڈی (TRX)",
    trx_help: "یہ آپ کو EasyPaisa کی تصدیقی SMS میں ملے گی۔",
    upload_receipt: "پیمنٹ رسید اپ لوڈ کرنے کے لیے کلک کریں",
    submit_receipt: "رسید جمع کریں",
    uploading: "اپ لوڈ ہو رہا ہے...",
    payment_submitted: "پیمنٹ جمع ہو گئی!",
    verify_note: "ہم آپ کی رسید کی تصدیق کر کے فوراً کام شروع کریں گے۔",
    invoice: "READZRAW — انوائس",
    billed_to: "بل برائے",
    package: "پیکج",
    delivery_window: "ڈیلیوری مدت",
    days_15: "15 دن",
    trx_id: "ٹرانزیکشن آئی ڈی",
    advance_paid: "ایڈوانس ادا شدہ (50%)",
    balance_delivery: "باقی رقم ڈیلیوری پر",
    invoice_note: "یہ انوائس محفوظ رکھیں — کسی بھی سپورٹ سوال کے لیے انوائس نمبر درکار ہوگا۔",
    questions: "سوالات؟ ہم سے رابطہ کریں",
    done: "ہو گیا",
    tc_title: "شرائط و ضوابط",
    tc_updated: "آخری تازہ کاری: 3 مارچ 2026",
    tc_s1_t: "1۔ شرائط کی قبولیت",
    tc_s1: "ReadzRaw کی ویب سائٹ اور خدمات استعمال کر کے آپ ان شرائط و ضوابط سے متفق ہوتے ہیں۔ اگر آپ متفق نہیں تو براہ کرم ہماری خدمات استعمال نہ کریں۔",
    tc_s2_t: "2۔ خدمات",
    tc_s2: "ReadzRaw پروفیشنل ویب ڈیولپمنٹ خدمات فراہم کرتا ہے جن میں لینڈنگ پیجز، بزنس ویب سائٹس، ای کامرس ویب سائٹس اور کسٹم ویب ایپلیکیشنز شامل ہیں۔",
    tc_s3_t: "3۔ آرڈرز اور پیمنٹس",
    tc_s3: "تمام آرڈرز کے لیے چیک آؤٹ کے دوران مقررہ ایڈوانس پیمنٹ درکار ہے۔ کام شروع ہونے کے بعد ایڈوانس رقم واپس نہیں ہوگی۔ مکمل ادائیگی پروجیکٹ مکمل ہونے اور حتمی ڈیلیوری سے پہلے واجب ہے۔",
    tc_s4_t: "4۔ کلائنٹ کی ذمہ داریاں",
    tc_s4: "کلائنٹ کو درست پروجیکٹ تقاضے، ضروری مواد (متن، تصاویر، برانڈنگ) اور بروقت فیڈبیک فراہم کرنا ہوگا۔ تاخیر سے ڈیلیوری کا وقت بڑھ سکتا ہے۔",
    tc_s5_t: "5۔ دانشی ملکیت",
    tc_s5: "مکمل ادائیگی پر کلائنٹ کے پروجیکٹ کے لیے بنایا گیا تمام کوڈ، ڈیزائن اور اثاثے کلائنٹ کو منتقل کر دیے جائیں گے۔ ReadzRaw مکمل پروجیکٹس کو پورٹ فولیو میں دکھانے کا حق رکھتا ہے۔",
    tc_s6_t: "6۔ ریویژنز",
    tc_s6: "ہر سروس پلان میں مخصوص ریویژن راؤنڈز شامل ہیں۔ اضافی ریویژنز پر اضافی چارجز لاگو ہو سکتے ہیں۔",
    tc_s7_t: "7۔ ذمہ داری کی حد",
    tc_s7: "ReadzRaw کسی بھی بالواسطہ نقصانات کا ذمہ دار نہیں ہوگا۔ ہماری مجموعی ذمہ داری کلائنٹ کی ادا کی گئی رقم تک محدود ہے۔",
    tc_s8_t: "8۔ معاہدے کی برخاستگی",
    tc_s8: "دونوں فریق تحریری نوٹس کے ساتھ پروجیکٹ معاہدہ ختم کر سکتے ہیں۔ برخاستگی کی صورت میں کلائنٹ مکمل شدہ کام کی ادائیگی کا پابند ہوگا۔ ایڈوانس پیمنٹ واپس نہیں ہوگی۔",
    tc_s9_t: "9۔ حکمران قانون",
    tc_s9: "یہ شرائط پاکستان کے قوانین کے مطابق ہیں۔ کسی بھی تنازع کو پہلے نیک نیتی سے بات چیت کے ذریعے حل کیا جائے گا۔",
    tc_s10_t: "10۔ رابطہ",
    tc_s10: "ان شرائط و ضوابط کے بارے میں سوالات کے لیے ہم سے رابطہ کریں",
  },
} as const;

export type DictKey = keyof (typeof dict)["en"];

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: DictKey) => string;
}

const LanguageContext = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  t: (k) => dict.en[k],
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    try {
      return (localStorage.getItem("rdz-lang") as Lang) || "en";
    } catch {
      return "en";
    }
  });
  const change = (l: Lang) => {
    setLang(l);
    try {
      localStorage.setItem("rdz-lang", l);
    } catch {}
  };
  const t = (k: DictKey) => dict[lang][k] ?? dict.en[k];
  return (
    <LanguageContext.Provider value={{ lang, setLang: change, t }}>
      <div dir={lang === "ur" ? "rtl" : "ltr"} className={lang === "ur" ? "font-urdu" : ""}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
